
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: GHS-MULTI -  - 
      The host system is: Linux - 6.13.8-arch1-1 - x86_64
...
